apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-redis
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexMeyerPMU/dojo-kubernetes-eks.git
    path: Kubernetes/guestbook-redis
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true