name: guestbook
services:
  guestbook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      "REDIS_HOST": "redis"
  redis:
    image: redis:7
    volumes:
      - "/redis"
volumes:
  redis:

