apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    app: guestbook
spec:
  selector:
    app: guestbook
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
    {{- if .Values.metrics.sidecar.enabled }}
    - name: metrics
      port: {{ .Values.metrics.sidecar.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
