apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
type: Opaque
stringData:
  github_token: "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"
  # To create this secret with your token, use:
  # kubectl create secret generic controller-manager \
  #   -n actions-runner-system \
  #   --from-literal=github_token=YOUR_GITHUB_PAT
