apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner
spec:
  # Number of runner pods to maintain
  replicas: 1
  
  template:
    spec:
      # REQUIRED: Specify your GitHub repository
      # Format: owner/repository-name
      repository: AlexMeyerPMU/dojo-kubernetes-eks
      
      # OR use organization-level runners (comment out repository above if using this)
      # organization: your-org-name
      
      # Optional: Custom labels for the runner
      # These labels can be used in your workflow with runs-on: [self-hosted, kubernetes, custom-label]
      labels:
        - self-hosted
        - kubernetes
        - linux
        - x64
      
      # Optional: Runner group (for enterprise)
      # group: "Default"
      
      # Optional: Enable Docker-in-Docker for container builds
      # This allows workflows to build and run Docker containers
      dockerdWithinRunnerContainer: true
      
      # Optional: Runner image (defaults to controller's default)
      # image: summerwind/actions-runner:latest
      
      # Optional: Resource limits for runner pods
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"
      
      # Optional: Environment variables for the runner
      # env:
      #   - name: CUSTOM_VAR
      #     value: "custom-value"
      
      # Optional: Node selector for pod placement
      # nodeSelector:
      #   kubernetes.io/os: linux
      
      # Optional: Tolerations for taints
      # tolerations:
      #   - key: "dedicated"
      #     operator: "Equal"
      #     value: "runners"
      #     effect: "NoSchedule"
      
      # Optional: Security context
      # securityContext:
      #   runAsUser: 1000
      #   fsGroup: 1000
      
      # Optional: Volume mounts for persistent data
      # volumeMounts:
      #   - name: runner-work
      #     mountPath: /runner/_work
      
      # volumes:
      #   - name: runner-work
      #     emptyDir: {}
---
# Optional: HorizontalRunnerAutoscaler for automatic scaling based on workflow queue
# Uncomment and configure if you want auto-scaling
# apiVersion: actions.summerwind.dev/v1alpha1
# kind: HorizontalRunnerAutoscaler
# metadata:
#   name: github-runner-autoscaler
# spec:
#   scaleTargetRef:
#     name: github-runner
#   minReplicas: 1
#   maxReplicas: 5
#   # Scale up when there are queued workflows
#   metrics:
#   - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
#     repositoryNames:
#     - AlexMeyerPMU/dojo-kubernetes-eks
#   # OR use percentage-based scaling
#   # - type: PercentageRunnersBusy
#   #   scaleUpThreshold: '0.75'
#   #   scaleDownThreshold: '0.3'
#   #   scaleUpFactor: '2'
#   #   scaleDownFactor: '0.5'
