name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
      - develop
    paths:
      - 'Docker/**'
      - '.github/workflows/docker-build-push.yaml'
  workflow_dispatch:  # Allow manual trigger

env:
  DOCKER_IMAGE_NAME: guestbook-go
  DOCKERFILE_PATH: Docker/Dockerfile
  BUILD_CONTEXT: Docker

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: [self-hosted, kubernetes]  # Use your self-hosted runner
    # Alternatively, use GitHub-hosted runner: runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
      
      - name: Image digest
        run: echo ${{ steps.meta.outputs.tags }}
